version: '3'

services:
  django_app:
    build: .
    volumes:
      - static_vol:/app/csc648_team1/my-app/build/static
      - media_vol:/app/csc648_team1/my-app/build/static/media
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/csc648_team1/my-app/build/static
      - media_vol:/app/csc648_team1/my-app/build/static/media
    ports:
      - "80:80"
    depends_on:
      - django_app

volumes:
  static_vol:
  media_vol:
